# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    multiple: false
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

# 言語指定 - 日本語
locale: 'ja'
# ワークフロー機能追加
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'ページ'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/pages/contact.md'
        label: 'お問い合わせ'
        name: 'contact-page'
        fields:
          - {
              label: 'テンプレート',
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: 'タイトル', name: title, widget: string }
          - {
              label: 'アイキャッチ画像',
              name: featuredImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: 'サブタイトル', name: subtitle, widget: markdown }
          - { label: '本文', name: body, widget: markdown }
          - { label: '住所', name: address, widget: text }
          - { label: '電話番号', name: phone, widget: string }
          - { label: 'メール', name: email, widget: string }
          - name: locations
            label: 'ロケーション'
            widget: list
            fields:
              - {
                  label: 'マップリンク',
                  name: mapLink,
                  widget: string,
                  required: false,
                  default: '',
                }
              - {
                  label: '緯度',
                  name: lat,
                  widget: string,
                  required: false,
                  delete: false,
                  default: '',
                }
              - {
                  label: '経度',
                  name: lng,
                  widget: string,
                  required: false,
                  delete: false,
                  default: '',
                }
          - label: 'メタ情報'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - {
                  label: 'タイトル',
                  name: title,
                  widget: string,
                  required: false,
                }
              - {
                  label: '詳細',
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: '正規 URL',
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/blog.md'
        label: '投稿'
        name: 'blog-page'
        fields:
          - {
              label: 'テンプレート',
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'blog' }
          - { label: 'タイトル', name: title, widget: string }
          - { label: 'アイキャッチ画像', name: featuredImage, widget: image }
          - { label: 'サブタイトル', name: subtitle, widget: markdown }
          - label: 'メタ情報'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - {
                  label: 'タイトル',
                  name: title,
                  widget: string,
                  required: false,
                }
              - {
                  label: '詳細',
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: '正規 URL',
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/components.md'
        label: 'コンポーネント'
        name: 'components-page'
        fields:
          - {
              label: 'テンプレート',
              name: template,
              widget: hidden,
              default: ComponentsPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'components' }
          - { label: 'タイトル', name: title, widget: string }
          - { label: 'アイキャッチ画像', name: featuredImage, widget: image }
          - { label: 'サブタイトル', name: subtitle, widget: markdown }
          - { label: 'セクション 1', name: section1, widget: markdown }
          - { label: 'セクション 2', name: section2, widget: markdown }
          - { name: video, label: 'ビデオ', widget: file }
          - { name: videoPoster, label: 'ビデオアイキャッチ', widget: image }
          - { label: 'ビデオタイトル', name: videoTitle, widget: string }
          - label: 'アコーディオン'
            name: 'accordion'
            widget: 'list'
            fields:
              - { name: 'タイトル', label: title, widget: string, default: '' }
              - { name: '詳細', label: description, widget: string }
          - label: 'ギャラリー'
            name: 'gallery'
            widget: 'list'
            fields:
              - { name: '画像', label: Image, widget: image }
              - { name: alt, label: Alt, widget: string }
              - {
                  label: 'タイトル',
                  name: title,
                  widget: string,
                  required: false,
                }
          - label: 'メタ情報'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - {
                  label: 'タイトル',
                  name: title,
                  widget: string,
                  required: false,
                }
              - {
                  label: '詳細',
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: '正規 URL',
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/home.md'
        label: 'ホーム'
        name: 'home-page'
        fields:
          - {
              label: 'テンプレート',
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: 'タイトル', name: title, widget: string }
          - { label: 'アイキャッチ画像', name: featuredImage, widget: image }
          - {
              label: 'サブタイトル',
              name: subtitle,
              widget: markdown,
              required: false,
            }
          - { label: '本文', name: body, widget: markdown }
          - label: 'アコーディオン'
            name: 'accordion'
            widget: 'list'
            required: false
            fields:
              - { label: 'タイトル', name: 'title', widget: 'string' }
              - { label: '本文', name: content, widget: text }
          - label: 'メタ情報'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - {
                  label: 'タイトル',
                  name: title,
                  widget: string,
                  required: false,
                }
              - {
                  label: '詳細',
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: '正規 URL',
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

  - name: infoPages
    label: 'インフォメーション'
    editor:
      preview: true
    folder: content/infoPages
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields:
      - {
          label: 'テンプレート',
          name: template,
          widget: hidden,
          default: DefaultPage,
        }
      - { label: Slug, name: slug, widget: string }
      - { label: 'タイトル', name: title, widget: string }
      - { label: 'アイキャッチ画像', name: featuredImage, widget: image }
      - { label: '本文', name: body, widget: markdown }
      - label: 'メタ情報'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: 'タイトル', name: title, widget: string, required: false }
          - { label: '詳細', name: description, widget: text, required: false }
          - {
              label: '正規 URL',
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: posts
    label: '投稿'
    editor:
      preview: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: 'テンプレート',
          name: template,
          widget: hidden,
          default: SinglePost,
        }
      - { label: 'タイトル', name: title, widget: string }
      - label: 'ステータス'
        name: 'status'
        widget: 'select'
        options: ['Published', 'Featured', 'Draft']
        default: 'Published'
      - { label: '日付', name: date, widget: date, format: 'YYYY-MM-DD' }
      - {
          label: 'アイキャッチ画像',
          name: featuredImage,
          widget: image,
          required: false,
        }
      - { label: '抜粋', name: excerpt, widget: text }
      - { label: '本文', name: body, widget: markdown }
      - label: 'カテゴリー'
        name: 'categories'
        widget: 'list'
        required: false
        fields:
          - label: 'カテゴリー'
            name: 'category'
            widget: 'relation'
            collection: 'postCategories'
            searchFields: ['title']
            valueField: 'title'
      - label: 'メタ情報'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: 'タイトル', name: title, widget: string, required: false }
          - { label: '詳細', name: description, widget: text, required: false }
          - {
              label: '正規 URL',
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: postCategories
    label: 'カテゴリー'
    editor:
      preview: false
    folder: content/postCategories
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: 'テンプレート',
          name: template,
          widget: hidden,
          default: BlogIndex,
        }
      - { label: 'タイトル', name: title, widget: string }
      - {
          label: 'サブタイトル',
          name: subtitle,
          widget: string,
          required: false,
        }
      - {
          label: 'アイキャッチ画像',
          name: featuredImage,
          widget: image,
          required: false,
        }
      - label: 'メタ情報'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: 'タイトル', name: title, widget: string, required: false }
          - { label: '詳細', name: description, widget: text, required: false }
          - {
              label: '正規 URL',
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  - name: 'settings'
    label: '設定'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'グローバル設定'
        name: 'global-settings'
        fields:
          - { label: 'サイトタイトル', name: siteTitle, widget: string }
          - {
              label: 'サイト URL',
              name: siteUrl,
              widget: string,
              required: false,
            }
          - {
              label: 'サイト詳細',
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: 'ソーシャルメディアカード'
            name: socialMediaCard
            widget: object
            fields:
              - { label: '画像', name: image, widget: image, required: false }
          - {
              label: 'Google Analytics トラッキング ID',
              name: googleTrackingId,
              widget: string,
              required: false,
            }
